In [1]:
import pandas as pd

df = pd.read_excel("../data/raw/online_retail.xlsx")

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [ ]:
print("=" * 60)
print("1. DATASET SIZE")
print("=" * 60)
print(df.shape)

print("\n" + "=" * 60)
print("2. COLUMN NAMES")
print("=" * 60)
print(df.columns.tolist())

print("\n" + "=" * 60)
print("3. DATA TYPES")
print("=" * 60)
print(df.dtypes)

print("\n" + "=" * 60)
print("4. MISSING VALUES")
print("=" * 60)
print(df.isnull().sum())

print("\n" + "=" * 60)
print("5. DUPLICATE ROWS")
print("=" * 60)
print(df.duplicated().sum())

print("\n" + "=" * 60)
print("6. QUANTITY STATISTICS")
print("=" * 60)
print(df["Quantity"].describe())

print("\n" + "=" * 60)
print("7. UNIT PRICE STATISTICS")
print("=" * 60)
print(df["UnitPrice"].describe())

print("\n" + "=" * 60)
print("8. NUMBER OF COUNTRIES")
print("=" * 60)
print(df["Country"].nunique())

print("\n" + "=" * 60)
print("9. TOP 10 COUNTRIES")
print("=" * 60)
print(df["Country"].value_counts().head(10))

print("\n" + "=" * 60)
print("10. UNIQUE CUSTOMERS")
print("=" * 60)
print(df["CustomerID"].nunique())

print("\n" + "=" * 60)
print("11. UNIQUE PRODUCTS")
print("=" * 60)
print(df["StockCode"].nunique())

============================================================
1. DATASET SIZE
============================================================
(541909, 8)

============================================================
2. COLUMN NAMES
============================================================
['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']

============================================================
3. DATA TYPES
============================================================
InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID            float64
Country                   str
dtype: object

============================================================
4. MISSING VALUES
============================================================
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

============================================================
5. DUPLICATE ROWS
============================================================
5268

============================================================
6. QUANTITY STATISTICS
============================================================
count    541909.000000
mean          9.552250
std         218.081158
min      -80995.000000
25%           1.000000
50%           3.000000
75%          10.000000
max       80995.000000
Name: Quantity, dtype: float64

============================================================
7. UNIT PRICE STATISTICS
============================================================
count    541909.000000
mean          4.611114
std          96.759853
min      -11062.060000
25%           1.250000
50%           2.080000
75%           4.130000
max       38970.000000
Name: UnitPrice, dtype: float64

============================================================
8. NUMBER OF COUNTRIES
============================================================
38

============================================================
9. TOP 10 COUNTRIES
============================================================
Country
United Kingdom    495478
Germany             9495
France              8557
EIRE                8196
Spain               2533
Netherlands         2371
Belgium             2069
Switzerland         2002
Portugal            1519
Australia           1259
Name: count, dtype: int64

============================================================
10. UNIQUE CUSTOMERS
============================================================
4372

============================================================
11. UNIQUE PRODUCTS
============================================================
4070

:

In [1]:
import pandas as pd

df = pd.read_excel("../data/raw/online_retail.xlsx")

In [2]:
data = df.copy()

In [3]:
data["IsReturn"] = data["InvoiceNo"].astype(str).str.startswith("C")

In [4]:
data["IsReturn"].value_counts()

IsReturn
False    532621
True       9288
Name: count, dtype: int64

In [5]:
returns = data[data["IsReturn"] == True].copy()

In [6]:
returns.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,IsReturn
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom,True
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom,True
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom,True
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom,True
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom,True

In [7]:
returns.shape

(9288, 9)

In [8]:
sales = data[data["IsReturn"] == False].copy()

In [9]:
sales.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,IsReturn
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,False
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,False
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,False
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,False
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,False

In [10]:
sales.shape

(532621, 9)

In [11]:
sales = sales.drop_duplicates().copy()
returns = returns.drop_duplicates().copy()

In [12]:
print("Sales duplicates:", sales.duplicated().sum())
print("Returns duplicates:", returns.duplicated().sum())

Sales duplicates: 0
Returns duplicates: 0

In [13]:
sales = sales[sales["UnitPrice"] > 0].copy()

In [14]:
sales["UnitPrice"].describe()

count    524878.000000
mean          3.922573
std          36.093028
min           0.001000
25%           1.250000
50%           2.080000
75%           4.130000
max       13541.330000
Name: UnitPrice, dtype: float64

In [15]:
sales = sales[sales["Quantity"] > 0].copy()

In [16]:
sales["Quantity"].describe()

count    524878.000000
mean         10.616600
std         156.280031
min           1.000000
25%           1.000000
50%           4.000000
75%          11.000000
max       80995.000000
Name: Quantity, dtype: float64

In [17]:
returns = returns[returns["UnitPrice"] > 0].copy()

In [18]:
sales["Revenue"] = sales["Quantity"] * sales["UnitPrice"]

In [19]:
returns["ReturnValue"] = (
    returns["Quantity"].abs() * returns["UnitPrice"]
)

In [20]:
sales["InvoiceDate"] = pd.to_datetime(sales["InvoiceDate"])

sales["Year"] = sales["InvoiceDate"].dt.year
sales["Month"] = sales["InvoiceDate"].dt.month
sales["MonthName"] = sales["InvoiceDate"].dt.month_name()
sales["DayOfWeek"] = sales["InvoiceDate"].dt.day_name()

In [21]:
returns["InvoiceDate"] = pd.to_datetime(returns["InvoiceDate"])

returns["Year"] = returns["InvoiceDate"].dt.year
returns["Month"] = returns["InvoiceDate"].dt.month
returns["MonthName"] = returns["InvoiceDate"].dt.month_name()
returns["DayOfWeek"] = returns["InvoiceDate"].dt.day_name()

In [22]:
sales = sales.dropna(subset=["Description"]).copy()
returns = returns.dropna(subset=["Description"]).copy()

In [23]:
customer_sales = sales.dropna(subset=["CustomerID"]).copy()

In [24]:
print("SALES DATASET")
print("=" * 40)
print("Rows:", len(sales))
print("Columns:", len(sales.columns))
print("Revenue:", sales["Revenue"].sum())

print("\nRETURNS DATASET")
print("=" * 40)
print("Rows:", len(returns))
print("Columns:", len(returns.columns))
print("Return value:", returns["ReturnValue"].sum())

SALES DATASET
========================================
Rows: 524878
Columns: 14
Revenue: 10642110.804000001

RETURNS DATASET
========================================
Rows: 9251
Columns: 14
Return value: 893979.73

In [25]:
print("Sales negative quantities:", (sales["Quantity"] < 0).sum())
print("Sales invalid prices:", (sales["UnitPrice"] <= 0).sum())
print("Sales duplicates:", sales.duplicated().sum())

print("Returns negative quantities:", (returns["Quantity"] < 0).sum())
print("Returns invalid prices:", (returns["UnitPrice"] <= 0).sum())
print("Returns duplicates:", returns.duplicated().sum())

Sales negative quantities: 0
Sales invalid prices: 0
Sales duplicates: 0
Returns negative quantities: 9251
Returns invalid prices: 0
Returns duplicates: 0

In [26]:
sales.to_csv(
    "../data/processed/clean_sales.csv",
    index=False
)

returns.to_csv(
    "../data/processed/returns.csv",
    index=False
)

In [27]:
import os

print(os.path.exists("../data/processed/clean_sales.csv"))
print(os.path.exists("../data/processed/returns.csv"))

True
True

In [28]:
sales_check = pd.read_csv("../data/processed/clean_sales.csv")
returns_check = pd.read_csv("../data/processed/returns.csv")

print(sales_check.shape)
print(returns_check.shape)

(524878, 14)
(9251, 14)

C:\Users\mailt\AppData\Local\Temp\ipykernel_32828\1248495836.py:1: DtypeWarning: Columns (0: InvoiceNo) have mixed types. Specify dtype option on import or set low_memory=False.
  sales_check = pd.read_csv("../data/processed/clean_sales.csv")

In [29]:
sales_check = pd.read_csv(
    "../data/processed/clean_sales.csv",
    dtype={"InvoiceNo": str}
)

returns_check = pd.read_csv(
    "../data/processed/returns.csv",
    dtype={"InvoiceNo": str}
)

print("Sales:", sales_check.shape)
print("Returns:", returns_check.shape)

Sales: (524878, 14)
Returns: (9251, 14)

In [30]:
print("Sales columns:")
print(sales_check.columns.tolist())

print("\nReturns columns:")
print(returns_check.columns.tolist())

Sales columns:
['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country', 'IsReturn', 'Revenue', 'Year', 'Month', 'MonthName', 'DayOfWeek']

Returns columns:
['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country', 'IsReturn', 'ReturnValue', 'Year', 'Month', 'MonthName', 'DayOfWeek']

In [31]:
print("\nSales revenue:")
print(sales_check["Revenue"].sum())

print("\nTotal return value:")
print(returns_check["ReturnValue"].sum())

Sales revenue:
10642110.804000001

Total return value:
893979.73

In [32]:
print("Original rows:", len(df))
print("Sales rows:", len(sales))
print("Returns rows:", len(returns))
print("Total processed:", len(sales) + len(returns))
print("Rows removed:", len(df) - len(sales) - len(returns))

Original rows: 541909
Sales rows: 524878
Returns rows: 9251
Total processed: 534129
Rows removed: 7780